--[[
this file is auto-generated by Configer Tools
]]

return 
{{"id","name","designName","layer","order"},
{{1,"Base","基础背景层","Default",100}
,{2,"Module","模块层","Default",200}
,{3,"Popup","弹出层","Default",300}
,{4,"Upper","上级层","Default",400}
,{5,"Cover","封面层","Default",500}
}}